name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version increment (patch, minor, major) or specific version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Version bump (workflow_dispatch only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
          git add package.json package-lock.json pnpm-lock.yaml || true
          git commit -m "Bump version to $(node -p "require('./package.json').version") [skip ci]"
          git tag v$(node -p "require('./package.json').version")
          git push origin HEAD:main
          git push origin --tags

      - name: Build
        run: pnpm build

      - name: Fake branch if detached HEAD (release only)
        if: github.event_name == 'release'
        run: git symbolic-ref HEAD refs/heads/main

      # - name: Git status debug
      #   run: |
      #     git status
      #     git diff

      - name: Publish to NPM
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
